config/urls.py
from django.contrib import admin
from django.urls import path

# Landing page and holiday view
from cal.views import Holiday, home
# Views to manage everything about users
from accounts.views import (
    member,
    member_list,
    member_add,
    member_edit,
    member_delete,
    member_search,
    activate,
    password_new,
    password_reset,
    MyPasswordChange,
    MyPasswordChangeDone,
    logout_view,
    Login,
    MyProfile,
    logout_view)
# Views to manage activities and events
from events.views import (
    activities,
    activities_list,
    activity_add,
    activity_edit,
    activity_delete,
    activity_search,
    events,
    events_list,
    event_add,
    event_edit,
    event_delete,
    event_multi_delete,
    event_to_confirm,
    event_refused,
    event_exchange_ok,
    event_no_exchange,
    events_mine,
    events_list_mine,
    event_swap,
    # event_search,
)

urlpatterns = [
    path('', home, name="home"),
    path('holiday/<int:year>/<str:region>/', Holiday.as_view(), name="holiday"),
    # Accounts URLs
    path('member/', member, name="member"),
    path('htmx/member-list/', member_list, name="member_list"),
    path('htmx/member-add/', member_add, name="member_add"),
    path('htmx/member/<pk>/edit/', member_edit, name="member_edit"),
    path('htmy/member/<pk>/delete/', member_delete, name="member_delete"),
    path('htmx/member-search/', member_search, name="member_search"),
    path('activate/<uidb64>/<token>/', activate, name="activate"),
    path('password-new/<type>/<uidb64>/<token>/', password_new, name="password_new"),
    path('password-reset/', password_reset, name="password_reset"),
    path('password-change/', MyPasswordChange.as_view(), name="my_password_change"),
    path('password-change-done/', MyPasswordChangeDone.as_view(), name="my_password_change_done"),
    path('logout/', logout_view, name="logoutview"),
    path('login/', Login.as_view(), name="login"),
    path('my_profile/', MyProfile.as_view(), name="myprofile"),
    # Activities URLs
    path('activities/', activities, name="activities"),
    path('htmx/activities-list/', activities_list, name="activities_list"),
    path('htmx/activity-add/', activity_add, name="activity_add"),
    path('htmx/activity/<pk>/edit/', activity_edit, name="activity_edit"),
    path('htmx/activity/<pk>/delete/', activity_delete, name="activity_delete"),
    path('htmx/activity-search/', activity_search, name="activity_search"),
    # Events URLs
    path('events/', events, name='events'),
    path('htmx/events_list/', events_list, name="events_list"),
    path('htmx/event-add/', event_add, name="event_add"),
    path('htmx/event/<pk>/edit/', event_edit, name="event_edit"),
    path('htmx/event/<pk>/delete/', event_delete, name="event_delete"),
    path('htmx/event-multi-delete/', event_multi_delete, name="event_multi_delete"),
    path('event/to-confirm/<pk>/', event_to_confirm, name="event_to_confirm"),
    path('event/refused/<pk>/', event_refused, name="event_refused"),
    path('event/exchange-confirmed/<pk>/<user>', event_exchange_ok, name="event_exchange_ok"),
    path('event/exchanged-refused/<pk>/<user>/', event_no_exchange, name="event_no_exchange"),
    path('events-mine/', events_mine, name="events_mine"),
    path('htmx/events_list_mine/', events_list_mine, name="events_list_mine"),
    path('htmx/event-swap/<pk>/', event_swap, name="event_swap"),
    # path('htmx/event-search/', event_search, name="event_search"),
    # Django backend
    path('mgmt/', admin.site.urls),
]

events/models.py
import unicodedata

from django.core.exceptions import ValidationError
from django.db import models

from accounts.models import CustomUser


class Activities(models.Model):
    TECHNICIAN = 2
    MANAGER = 4
    SUPERVISOR = 6
    SUPERUSER = 8
    ACTIVITY_LEVEL = [
        (TECHNICIAN, 'Techniker'),
        (MANAGER, 'Manager'),
        (SUPERVISOR, 'Supervisor'),
        (SUPERUSER, 'Superuser'),
    ]

    name = models.CharField(max_length=100, unique=True)
    short_name = models.CharField(max_length=3, unique=True)
    activity_class = models.CharField(max_length=100, unique=True)
    background_color = models.CharField(max_length=9, blank=True)
    text_color = models.CharField(max_length=9, blank=True)
    level = models.IntegerField(choices=ACTIVITY_LEVEL, default=2, verbose_name='Stufe')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.name = self.name.title()
        self.short_name = self.short_name.upper()
        self.activity_class = self.name.replace('-', '').replace('/', '').lower()
        self.activity_class = self.strip_accents(self.activity_class)
        if len(self.activity_class.split()) > 1:
            self.activity_class = '_'.join(self.activity_class.split())
        super().save(*args, **kwargs)

    def strip_accents(self, text):
        text = unicodedata.normalize('NFKD', text).encode('ascii', 'ignore').decode('utf-8')
        return str(text)


class Events(models.Model):
    user_id = models.ForeignKey(CustomUser, on_delete=models.PROTECT)
    activity_id = models.ForeignKey(Activities, on_delete=models.PROTECT)
    date_start = models.DateField()
    date_stop = models.DateField()
    is_active = models.BooleanField()
    confirmed = models.BooleanField()
    displayed = models.BooleanField()
    suspended = models.BooleanField(default=False)
    changed_on = models.DateTimeField(auto_now=True)
    comment = models.TextField(max_length=300, blank=True)

events/views.py
import copy

from datetime import date, datetime
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.tokens import default_token_generator
from django.core.exceptions import ValidationError
from django.core.mail import send_mail
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.template.loader import render_to_string
from django.urls import reverse
from django.views.decorators.http import require_http_methods


from accounts.models import CustomUser

from .forms import ActivityForm, EventAddForm, EventEditForm, EventSwapForm
from .models import Activities, Events
from .utils import activity_to_css, admin_emails

@user_passes_test(lambda u: u.role >= CustomUser.SUPERVISOR)
def activities(request):
    return render(request, 'events/activities.html')


@user_passes_test(lambda u: u.role >= CustomUser.SUPERVISOR)
def activities_list(request):
    activities = Activities.objects.all().order_by('name')
    return render(request, 'events/activities_list.html', {'activities': activities})


@user_passes_test(lambda u: u.role >= CustomUser.SUPERVISOR)
def activity_add(request):
    if request.method == 'POST':
        form = ActivityForm(request.POST)
        if form.is_valid():
            activity = form.save()
            activity_to_css()
            messages.success(request, f'Aktivität {activity.name} erfolgreich hinzugefügt.')
            return HttpResponse(status=204, headers={'HX-Trigger': 'activitiesListChanged'})
    else:
        form = ActivityForm()
    return render(request, 'events/activity_add_form.html', {'form': form})


@user_passes_test(lambda u: u.role >= CustomUser.SUPERVISOR)
def activity_edit(request, pk):
    activity = get_object_or_404(Activities, pk=pk)
    if request.method == 'POST':
        form = ActivityForm(request.POST, instance=activity)
        if form.is_valid():
            activity = form.save()
            activity_to_css()
            messages.success(request, f'{activity.name} geändert.')
            return HttpResponse(status=204, headers={'HX-Trigger': 'activitiesListChanged'})
    else:
        form = ActivityForm(instance=activity)
    return render(request, 'events/activity_add_form.html', {
        'form': form,
        'activity': activity,
    })


@user_passes_test(lambda u: u.role >= CustomUser.SUPERVISOR)
@require_http_methods(["POST"])
def activity_delete(request, pk):
    activity = get_object_or_404(Activities, pk=pk)
    if request.method == 'POST':
        activity.delete()
        activity_to_css()
        messages.error(request, f'{activity.name} wurde gelöscht.')
        return HttpResponse(status=204, headers={'HX-Trigger': 'activitiesListChanged'})


@user_passes_test(lambda u: u.role >= CustomUser.SUPERVISOR)
def activity_search(request):
    search_text = request.POST.get('search_activity')

    results = Activities.objects.filter(Q(name__icontains=search_text) |
                                        Q(short_name__icontains=search_text)).order_by('name')
    return render(request, 'events/activities_list.html', {'results': results})


@login_required
def events(request):
    user = request.user
    return render(request, 'events/events.html', {'user': user})


@login_required
def events_list(request):
    events = Events.objects.filter(date_stop__gte=datetime.now().strftime('%Y-%m-%d')).order_by('date_start')
    return render(request, 'events/events_list.html', {'events': events})


@login_required
def event_add(request):
    if request.method == 'POST':
        form = EventAddForm(request.POST, user=request.user)
        if form.is_valid():
            user = request.user
            event = form.save(commit=False)
            activity = event.activity_id.name
            event.comment = f'{event.user_id}:\n{event.activity_id} von {event.date_start.strftime("%d.%m.%Y").strip("0")} bis {event.date_stop.strftime("%d.%m.%Y").strip("0")}'
            check_events = Events.objects.filter(date_start__lte=event.date_stop, date_stop__gte=event.date_start, confirmed=True)
            event.save()
            if user.role < CustomUser.MANAGER and (activity == 'Ferien' or activity == 'Kompensation'):
                message = render_to_string('email/event_validation_email.html', {
                    'domain': settings.DEFAULT_DOMAIN,
                    'event': event,
                    'check_events': check_events,
                })
                subject = 'Ein neuer Event bittet um Ihre Aufmerksamkeit.'
                subject = ''.join(subject.splitlines())
                send_mail(subject, message, event.user_id.email, admin_emails())
            messages.success(request, f'Event {event.activity_id} erfolgreich hinzugefügt.')
            return HttpResponse(status=204, headers={'HX-Trigger': 'eventsListChanged'})
    else:
        form = EventAddForm(user=request.user)
    return render(request, 'events/event_add_form.html', {'form': form})


@login_required
def event_edit(request, pk):
    event = get_object_or_404(Events, pk=pk)
    user = request.user
    if request.method == 'POST':
        form = EventEditForm(request.POST, instance=event, user=user)
        if form.is_valid():
            old_obj = Events.objects.get(pk=event.pk)
            form.save(commit=False)
            if (event.activity_id.name == 'Dispatcher' or event.activity_id.name == 'Pikett') and user.role < CustomUser.MANAGER:
                if Events.objects.filter(user_id=event.user_id, date_start__lte=event.date_stop, date_stop__gte=event.date_start):
                    messages.error(request, f'{event.user_id} ist zu dieser Zeit bereits beschäftigt.')
                    return HttpResponse(status=204, headers={'HX-Trigger': 'eventsListChanged'})
                else:
                    message = render_to_string('email/exchange_validation_email.html', {
                        'domain': settings.DEFAULT_DOMAIN,
                        'event': event,
                        'user': user,
                    })
                    subject = 'Antrag auf Austausch von Aktivitäten.'
                    subject = ''.join(subject.splitlines())
                    send_mail(subject, message, event.user_id.email, admin_emails())
                    event.suspended = True
                    event.save()
                    messages.warning(request, f'{event.user_id} muss den Austausch noch bestätigen.')
                    return HttpResponse(status=204, headers={'HX-Trigger': 'eventsListChanged'})
            if event.activity_id.name == 'Ferien':
                if event.confirmed == True and event.is_active == True:
                    event.comment = f'{event.user_id}:\n{event.activity_id} Change: von {event.date_start.strftime("%d.%m.%Y").strip("0")} bis {event.date_stop.strftime("%d.%m.%Y").strip("0")}'
                    if (event.date_start < old_obj.date_start or event.date_stop > old_obj.date_stop):
                        event.confirmed = False
                        check_events = Events.objects.filter(date_start__lte=event.date_stop, date_stop__gte=event.date_start, confirmed=True)
                        message = render_to_string('email/event_validation_email.html', {
                            'domain': settings.DEFAULT_DOMAIN,
                            'event': event,
                            'check_events': check_events,
                        })
                        subject = 'Ein Event wurde geändert und bittet um Ihre Aufmerksamkeit.'
                        subject = ''.join(subject.splitlines())
                        send_mail(subject, message, event.user_id.email, admin_emails())
            else:
                event.comment = f'{event.user_id}:\n{event.activity_id} Change: von {event.date_start.strftime("%d.%m.%Y").strip("0")} bis {event.date_stop.strftime("%d.%m.%Y").strip("0")}'
            event.save()
            messages.success(request, f'{event.activity_id} von {event.user_id} geändert.')
            return HttpResponse(status=204, headers={'HX-Trigger': 'eventsListChanged'})
    else:
        form = EventEditForm(instance=event, user=user)
    return render(request, 'events/event_edit_form.html', {
        'form': form,
        'event': event,
        'user': user
    })


@login_required
@require_http_methods(["POST"])
def event_delete(request, pk):
    event = get_object_or_404(Events, pk=pk)
    if request.method == 'POST':
        if str(event.date_start) > datetime.now().strftime('%Y-%m-%d'):
            event.delete()
            messages.error(request, f'{event.activity_id} von {event.user_id} wurde gelöscht.')
            return HttpResponse(status=204, headers={'HX-Trigger': 'eventsListChanged'})
        messages.warning(request, 'Das Event muss in der Zukunft liegen, damit es gelöscht werden kann.')
        return HttpResponse(status=204, headers={'HX-Trigger': 'eventsListChanged'})


@login_required
@require_http_methods(["POST"])
def event_multi_delete(request):
    if request.method == 'POST':
        ids = request.POST.getlist('event_check')
        for id in ids:
            event = get_object_or_404(Events, pk=id)
            event.delete()
        messages.error(request, 'Alle ausgewählten Events wurden gelöscht.')
        return HttpResponse(status=204, headers={'HX-Trigger': 'eventsListChanged'})


@login_required
@user_passes_test(lambda u: u.role >= CustomUser.SUPERVISOR)
def event_to_confirm(request, pk):
    event = get_object_or_404(Events, pk=pk)
    event.confirmed = event.is_active = event.displayed = True
    event.save()
    message = render_to_string('email/event_confirmation_email.html', {
        'domain': settings.DEFAULT_DOMAIN,
        'event': event,
    })
    subject = 'Ihr Antrag wurde bestätigt!'
    subject = ''.join(subject.splitlines())

templates/events/activities.html
{% extends 'base.html' %}

{% block title %}Activities{% endblock title %}

{% block activities_active %}active{% endblock activities_active %}

{% block content %}
<h4 class="my-4">Aktivitäten Liste</h4>
<div class="w-50">
    <div class="d-flex justify-content-start my-3">
        <button type="button" class="btn btn-outline-primary me-auto" hx-get="{% url 'activity_add' %}" hx-target="#dialog"><i class="fa-solid fa-plus"></i></button>
        <div class="d-flex col-4">
            <input type="search"
                id="search_activity"
                class="form-control"
                name="search_activity"
                placeholder="Suchen..."
                hx-post="{% url 'activity_search' %}"
                hx-trigger="keyup changed delay:500ms"
                hx-target="#activities_list">
            <a href="{% url 'activities' %}" class="btn btn-outline-secondary ms-2">
                <i class="fa-solid fa-rotate-left"></i>
            </a>
        </div>
    </div>
    <div id="activities_list" class="d-flex justify-content-center" hx-get="{% url 'activities_list' %}" hx-trigger="load, activitiesListChanged from:body">
        <!-- Inject htmx activities_list.html -->
    </div>
</div>
{% endblock content %}

templates/events/activities_list.html
<table class="table mt-2">
    <thead>
        <tr>
            <th>Name</th>
            <th class="text-center">Abkürzung</th>
            <th>Hintergrund</th>
            <th>Text</th>
            <th>Stufe</th>
            <th class="text-center">Ergebnis</th>
            <th colspan="2" class="text-center">Aktion</th>
        </tr>
    </thead>
    <tbody>
        {% for activity in activities %}
        <tr>
            <td class="align-middle">{{ activity.name|title }}</td>
            <td class="align-middle text-center">{{ activity.short_name }}</td>
            <td class="align-middle">{{ activity.background_color }}</td>
            <td class="align-middle">{{ activity.text_color }}</td>
            <td class="align-middle">{{ activity.get_level_display }}</td>
            <td class="text-center">
                <div class="py-1 mx-4 rounded {{ activity.activity_class }}">
                    {{ activity.short_name }}
                </div>
            </td>
            <td class="text-center align-middle">
                <button type="button" class="btn btn-sm text-primary" hx-get="{% url 'activity_edit' activity.id %}" hx-target="#dialog">
                    <i class="fa-solid fa-pen"></i>
                </button>
            </td>
            <td class="text-center align-middle">
                <button type="button" class="btn btn-sm text-danger" hx-post="{% url 'activity_delete' activity.id %}" hx-confirm="Willst du {{ activity.name }} wirklich löschen?">
                    <i class="fa-solid fa-trash"></i>
                </button>
            </td>
        </tr>
        {% endfor %}
        {% for result in results %}
        <tr>
            <td class="align-middle">{{ result.name|title }}</td>
            <td class="align-middle text-center">{{ result.short_name }}</td>
            <td class="align-middle">{{ result.background_color }}</td>
            <td class="align-middle">{{ result.text_color }}</td>
            <td class="align-middle">{{ result.get_level_display }}</td>
            <td class="text-center">
                <div class="py-1 mx-4 rounded {{ result.activity_class }}">
                    {{ result.short_name }}
                </div>
            </td>
            <td class="text-center align-middle">
                <button type="button" class="btn btn-sm text-primary" hx-get="{% url 'activity_edit' result.id %}" hx-target="#dialog">
                    <i class="fa-solid fa-pen"></i>
                </button>
            </td>
            <td class="text-center align-middle">
                <button type="button" class="btn btn-sm text-danger" hx-post="{% url 'activity_delete' result.id %}" hx-confirm="Willst du {{ result.name }} wirklich löschen?">
                    <i class="fa-solid fa-trash"></i>
                </button>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

templates/events/activity_add_form.html
{% load crispy_forms_tags %}
<div class="modal-content">
    <form hx-post="{{ request.path }}" class="p-2" autocomplete="off" novalidate enctype="multipart/form-data">
        {% csrf_token %}
        <div class="text-center modal-header">
            <h4 class="modal-title">Neue Aktivität</h4>
        </div>
        <div class="modal-body">
            <div class="row mb-2">
                <div class="col-6">
                    {{ form.name|as_crispy_field }}
                </div>
                <div class="col-6">
                    {{ form.short_name|as_crispy_field }}
                </div>
            </div>
            <div class="row mb-2">
                <div class="d-flex justify-content-start col-6">
                    <input id="bg_color" type="color" name="background_color" class="form-control form-control-color" value="{% if activity %}{{ activity.background_color }}{% endif %}">
                    <label for="bg_color" class="ms-2 pt-1">Hintergrund</label>
                </div>
                <div class="d-flex justify-content-start col-6">
                    <input id="txt_color" type="color" name="text_color" class="form-control form-control-color" value="{% if activity %}{{ activity.text_color }}{% endif %}">
                    <label for="txt_color" class="ms-2 pt-1">Text</label>
                </div>
            </div>
            <div class="row mb-2">
                <div>
                    {{ form.level|as_crispy_field }}
                </div>
            </div>
        </div>
        <div class="d-flex justify-content-end modal-footer">
            <button type="button" class="btn btn-sm btn-outline-secondary me-2" data-bs-dismiss="modal">
                <i class="fa-solid fa-backward"></i>
            </button>
            <button type="submit" class="btn btn-sm btn-outline-primary">
                <i class="fa-solid fa-floppy-disk"></i>
            </button>
        </div>
    </form>
</div>

templates/events/event_add_form.html
{% load crispy_forms_tags %}
<div class="modal-content">
    <form hx-post="{{ request.path }}" class="p-2" autocomplete="off" novalidate enctype="multipart/form-data">
        {% csrf_token %}
        <div class="text-center modal-header">
            <h4 class="modal-title">Neuer Event</h4>
        </div>
        <div class="modal-body">
            <div class="row mb-2">
                {% for error in form.non_field_errors %}
                <div class="alert alert-block alert-danger">
                    {{ error|linebreaks }}
                </div>
                {% endfor %}
            </div>
            <div class="row mb-2">
                <div class="col-6">
                    {{ form.user_id|as_crispy_field }}
                </div>
                <div class="col-6">
                    {{ form.activity_id|as_crispy_field }}
                </div>
            </div>
            <div class="row mb-2">
                <div class="col-6">
                    {{ form.date_start|as_crispy_field }}
                </div>
                <div class="col-6">
                    {{ form.date_stop|as_crispy_field }}
                </div>
            </div>
            <div class="row mb-2">
                <div class="col-4">
                    {{ form.confirmed|as_crispy_field }}
                </div>
                <div class="col-4">
                    {{ form.is_active|as_crispy_field }}
                </div>
                <div class="col-4">
                    {{ form.displayed|as_crispy_field }}
                </div>
            </div>
        </div>
        <div class="d-flex justify-content-end modal-footer">
            <button type="button" class="btn btn-sm btn-outline-secondary me-2" data-bs-dismiss="modal">
                <i class="fa-solid fa-backward"></i>
            </button>
            <button type="submit" class="btn btn-sm btn-outline-primary">
                <i class="fa-solid fa-floppy-disk"></i>
            </button>
        </div>
    </form>
</div>

templates/events/event_edit_form.html
{% load crispy_forms_tags %}
<div class="modal-content">
    <form hx-post="{{ request.path }}" class="p-2" autocomplete="off" novalidate enctype="multipart/form-data">
        {% csrf_token %}
        <div class="text-center modal-header">
            <h4 class="modal-title">Event ändern</h4>
        </div>
        <div class="modal-body">
            <div class="row mb-2">
                {% for error in form.non_field_errors %}
                <div class="alert alert-block alert-danger">
                    {{ error|linebreaks }}
                </div>
                {% endfor %}
            </div>
            <div class="row mb-2">
                <div class="col-6">
                    {{ form.user_id|as_crispy_field }}
                </div>
                <div class="col-6">
                    {{ form.activity_id|as_crispy_field }}
                </div>
            </div>
            <div class="row mb-2">
                <div class="col-6">
                    {{ form.date_start|as_crispy_field }}
                </div>
                <div class="col-6">
                    {{ form.date_stop|as_crispy_field }}
                </div>
            </div>
            <div class="row mb-2">
                <div class="col-4">
                    {{ form.confirmed|as_crispy_field }}
                </div>
                <div class="col-4">
                    {{ form.is_active|as_crispy_field }}
                </div>
                <div class="col-4">
                    {{ form.displayed|as_crispy_field }}
                </div>
            </div>
            {% if user.role > 4 %}
            <div class="row mb-2">
                <div class="col-12">
                    {{ form.comment|as_crispy_field }}
                </div>
            </div>
            {% endif %}
        </div>
        <div class="d-flex justify-content-end modal-footer">
            <button type="button" class="btn btn-sm btn-outline-secondary me-2" data-bs-dismiss="modal">
                <i class="fa-solid fa-backward"></i>
            </button>
            <button type="submit" class="btn btn-sm btn-outline-primary">
                <i class="fa-solid fa-floppy-disk"></i>
            </button>
        </div>
    </form>
</div>

templates/events/event_permanent_removal.html
{% extends 'base.html' %}

{% block title %}Permanent Removal{% endblock title %}

{% block events_active %}active{% endblock events_active %}

{% block content %}
<h4 class="my-4">Events endgültige Löschung</h4>
<div class="container">
    <form method="POST" action="{% url 'event_permanent_removal' %}">
        {% csrf_token %}
        <div class="d-flex justify-content-end">
            <button type="submit" class="btn btn-outline-danger">Alles löschen</button>
        </div>
        <div class="d-flex justify-content-center">
            <table class="table table-striped mt-2">
                <thead>
                    <tr>
                        <th class="align-middle">#</th>
                        <th class="align-middle">Benutzer</th>
                        <th class="align-middle">Aktivität</th>
                        <th class="align-middle">Von</th>
                        <th class="align-middle">Bis</th>
                        <th class="align-middle">Geändert am</th>
                        <th class="align-middle">Kommentar</th>
                    </tr>
                </thead>
                <tbody>
                        {% for event in oldEvents %}
                        <tr>
                            <td>{{ event.id }}</td>
                            <td>{{ event.user_id }}</td>
                            <td>{{ event.activity_id }}</td>
                            <td>{{ event.date_start|date:"j.m.Y" }}</td>
                            <td>{{ event.date_stop|date:"j.m.Y" }}</td>
                            <td>{{ event.changed_on|date:"j.m.Y - G:i" }}</td>
                            <td>{{ event.comment|linebreaksbr }}</td>
                        </tr>
                        {% endfor %}
                </tbody>
            </table>
        </div>
    </form>
</div>



{% endblock content %}

templates/events/event_swap_form.html
{% load crispy_forms_tags %}
<div class="modal-content">
    <form hx-post="{{ request.path }}" class="p-2" autocomplete="off" novalidate enctype="multipart/form-data">
        {% csrf_token %}
        <div class="text-center modal-header">
            <h4 class="modal-title">Event-Austausch</h4>
        </div>
        <div class="modal-body">
            <div class="row mb-2">
                {% for error in form.non_field_errors %}
                <div class="alert alert-block alert-danger">
                    {{ error|linebreaks }}
                </div>
                {% endfor %}
            </div>
            <div class="row mb-2">
                <div class="col-12">
                    <p>
                        {{ event.activity_id }} von {{ event.date_start }} bis {{ event.date_stop }}
                    </p>

                </div>
            </div>
            <div class="row mb-2">
                <div class="col-12">
                    {{ form }}
                </div>
            </div>
        </div>
        <div class="d-flex justify-content-end modal-footer">
            <button type="button" class="btn btn-sm btn-outline-secondary me-2" data-bs-dismiss="modal">
                <i class="fa-solid fa-backward"></i>
            </button>
            <button type="submit" class="btn btn-sm btn-outline-primary">
                <i class="fa-regular fa-paper-plane"></i>
            </button>
        </div>
    </form>
</div>

templates/events/events.html
{% extends 'base.html' %}

{% block title %}Events{% endblock title %}

{% block events_active %}active{% endblock events_active %}

{% block content %}
<h4 class="my-4">Events Liste</h4>
<div class="w-100 px-5">
    <div class="d-flex justify-content-start my-3">
        <button type="button" class="btn btn-outline-primary me-auto" hx-get="{% url 'event_add' %}" hx-target="#dialog"><i class="fa-solid fa-calendar-plus"></i></button>
        <div class="d-flex col-2">
            {% comment %}
            <input type="search"
            id="search_event"
            class="form-control"
            name="search_event"
            placeholder="Suchen..."
            hx-post="{% url 'event_search' %}"
            hx-trigger="keyup changed delay:500ms"
            hx-target="#events_list">
            <a href="{% url 'events' %}" class="btn btn-outline-secondary ms-2">
                <i class="fa-solid fa-rotate-left"></i>
            </a>
            {% endcomment %}
        </div>
    </div>
    {% if user.role > 4 %}
    <div class="d-flex justify-content-start my-3">
        <button id="checkallbtn" type="button" class="btn btn-outline-secondary me-auto">
            <i class="fa-solid fa-check-double"></i>
        </button>
        <button id="deleteallbtn" type="button" class="btn btn-outline-danger" hx-include="#checked_events" hx-post="{% url 'event_multi_delete' %}" hx-confirm="Willst du wirklich alle ausgewählten Events löschen?">
            <i class="fa-regular fa-trash-can"></i>&nbsp;<i class="fa-solid fa-plus"></i>
        </button>
    </div>
    {% endif %}
    <div id="events_list" class="d-flex justify-content-center" hx-get="{% url 'events_list' %}" hx-trigger="load, eventsListChanged from:body">
        <!-- Inject htmx events_list.html -->
    </div>
</div>


{% endblock content %}